// Mocks generated by Mockito 5.3.2 from annotations
// in posts/test/features/postsapp/domain/usescases/get_post_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:posts/core/error/faliures.dart' as _i5;
import 'package:posts/features/postapp/domain/entities/posts.dart' as _i6;
import 'package:posts/features/postapp/domain/repositories/post_repository.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [PostRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockPostRepository extends _i1.Mock implements _i3.PostRepository {
  MockPostRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Faliure, List<_i6.Post>>> getPostList() =>
      (super.noSuchMethod(
        Invocation.method(
          #getPostList,
          [],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Faliure, List<_i6.Post>>>.value(
            _FakeEither_0<_i5.Faliure, List<_i6.Post>>(
          this,
          Invocation.method(
            #getPostList,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Faliure, List<_i6.Post>>>);
}
