// Mocks generated by Mockito 5.3.2 from annotations
// in posts/test/features/postsapp/date/repository/photo_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:posts/core/network/network_info.dart' as _i6;
import 'package:posts/features/postapp/date/datasources/photo_local_data_source.dart'
    as _i5;
import 'package:posts/features/postapp/date/datasources/photo_remote_data_source.dart'
    as _i2;
import 'package:posts/features/postapp/date/models/photo_model.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [PhotoRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockPhotoRemoteDataSource extends _i1.Mock
    implements _i2.PhotoRemoteDataSource {
  MockPhotoRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.PhotoModel>> getPhotoList(dynamic albumId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPhotoList,
          [albumId],
        ),
        returnValue: _i3.Future<List<_i4.PhotoModel>>.value(<_i4.PhotoModel>[]),
      ) as _i3.Future<List<_i4.PhotoModel>>);
}

/// A class which mocks [PhotoLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockPhotoLocalDataSource extends _i1.Mock
    implements _i5.PhotoLocalDataSource {
  MockPhotoLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.PhotoModel>> getLastPhotoList() => (super.noSuchMethod(
        Invocation.method(
          #getLastPhotoList,
          [],
        ),
        returnValue: _i3.Future<List<_i4.PhotoModel>>.value(<_i4.PhotoModel>[]),
      ) as _i3.Future<List<_i4.PhotoModel>>);
  @override
  _i3.Future<void> cachePhotoList(List<_i4.PhotoModel>? photoToCache) =>
      (super.noSuchMethod(
        Invocation.method(
          #cachePhotoList,
          [photoToCache],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}

/// A class which mocks [NetworkInfo].
///
/// See the documentation for Mockito's code generation for more information.
class MockNetworkInfo extends _i1.Mock implements _i6.NetworkInfo {
  MockNetworkInfo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<bool> get isConnected => (super.noSuchMethod(
        Invocation.getter(#isConnected),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);
}
